version: "3.8"

##Utilizamos a imagem 'nginx-alpine' do Docker Hub para o servidor Nginx. Configuramos volumes e portas com base na documentação e configuramos dependências para criá-lo em conjunto com o PHP e o MySQL
services:
  nginx:
    image: 'nginx:stable-alpine'
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
##Utilizamos a imagem PHP do Docker, criada com base em arquivos Docker, e a imagem MySQL do Docker Hub, configurando as portas de acordo com a documentação
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - '3000:9000'

  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
##O contêiner Composer é usado para baixar os arquivos necessários para executar as dependências do Laravel
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html

  #artisan:
  #npm:
